Initial nft pallet
anmolnetwork/anmol-node pull request #18
Opened 2021-05-18 12:11 UTC by korzewski

Closes #6

2021-05-18 13:05 UTC, aelesbao commented on pallets/nft/Cargo.toml
> +version = '0.1.0'
Let's keep the header consistent with the other `Cargo.toml` files (like the [kiities-pallet](https://github.com/anmolnetwork/anmol-node/blob/master/pallets/kitties/Cargo.toml#L2-L10))

2021-05-18 16:57 UTC, nblogist requested changes
@korzewski check fails can you please check the issue.

2021-05-19 12:18 UTC, korzewski commented
All request changes seems to be done, please review again

2021-05-19 14:36 UTC, nblogist approved these changes
Looks good! @aelesbao please add your review.

2021-05-20 11:52 UTC, aelesbao approved these changes
lgtm!

2021-05-20 11:52 UTC, merged