Korzewski/feature/29 offchain storage
anmolnetwork/anmol-node pull request #30
Opened 2021-06-15 15:16 UTC by korzewski

Closes #29

2021-06-17 18:49 UTC, korzewski commented
This PR contains some cleanup like files splitting.

Quick overview what happen with NFT flow:
- User call `nft_request()`, this add it to `PendingNftQueue` (on-chain)
- `on_finalize()` copy `PendingNftQueue` to offchain storage `new_nft_requests`. Then clean up onchain `PendingNftQueue` so it's never added to block. I'm using it only as communication layer
- From here everything is offchain storage.` offchain hook_init()` is executed after each block. First we update `nft_pending_queue` by pushing all `new_nft_requests`
- Now `nft_pending_queue` is up to date and we can use it as before
- Main purpose of `pending queue` in offchain worker is the case of additional http requests or other heavy computations

This may be useful for all metadata storage. On-chain would keep only `key_hash` which is offchain storage database index key where we can keep more data without being worry of on-chain storage size.

I've decided to do not write more unit tests at this stage. We may need to rewrite it slightly when final direction is made.

2021-06-21 08:56 UTC, PierreOssun approved these changes, later dismissed
Good for me

2021-06-22 22:02 UTC, aelesbao requested changes

2021-06-22 22:02 UTC, aelesbao commented on pallets/nft/src/lib.rs
> +			PendingNftQueue::<T>::put(PendingNftQueueOf::<T>::new());
Any reason why you didn't use `PendingNftQueue::<T>::mutate()` here instead?

2021-06-22 22:02 UTC, aelesbao commented on pallets/nft/src/lib.rs
> +			let pending_nft_queue = PendingNftQueue::<T>::get();
What happens here on the first access when there's no value stored?

2021-06-22 22:02 UTC, aelesbao commented on pallets/nft/src/local_storage.rs
> +}
I'm not sure if we added it to the coding guidelines, but it's [always a good idea to leave a newline at the end of the file](https://unix.stackexchange.com/a/18789/370378). 😃

2021-06-22 22:02 UTC, aelesbao commented on pallets/nft/src/offchain.rs
> +                }
Why don't you loop through the queue here?

2021-06-22 22:02 UTC, aelesbao commented on pallets/nft/src/offchain.rs
> +}
Same here about a newline at the EOF.

2021-06-23 13:48 UTC, nblogist commented on pallets/nft/src/local_storage.rs
> +}
Thank you! Coding guidelines have been updated

2021-06-24 10:16 UTC, nblogist requested changes
After other reviews are finalized and #34 is merged, please merge `ibtida` to your branch.

2021-06-25 08:36 UTC, korzewski commented on pallets/nft/src/lib.rs
> +			PendingNftQueue::<T>::put(PendingNftQueueOf::<T>::new());
Good point

2021-06-25 08:41 UTC, korzewski commented on pallets/nft/src/lib.rs
> +			let pending_nft_queue = PendingNftQueue::<T>::get();
It will get a default value which is empty `Vec` of type `PendingNft`

2021-06-25 12:17 UTC, nblogist approved these changes, later dismissed

2021-06-27 22:28 UTC, aelesbao submitted a review, later dismissed
LGTM

2021-06-29 07:21 UTC, korzewski commented
All was accepted before `ibtida` merge. Should be good to go now

2021-06-29 07:54 UTC, aelesbao approved these changes

2021-06-29 09:12 UTC, nblogist approved these changes
Looks good

2021-06-29 09:12 UTC, merged